// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUMb24P7TtfpvnEu9WJ-NJlVpj7_tPps',
    appId: '1:422986280730:web:116a3dd2aec2cb9a8706a3',
    messagingSenderId: '422986280730',
    projectId: 'ilkmobilapp',
    authDomain: 'ilkmobilapp.firebaseapp.com',
    storageBucket: 'ilkmobilapp.firebasestorage.app',
    measurementId: 'G-TFDL8RG2TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vbg7vYf6rzO-NnS6KqBTPzmzQRe-USY',
    appId: '1:422986280730:android:4d1aba33565bd3008706a3',
    messagingSenderId: '422986280730',
    projectId: 'ilkmobilapp',
    storageBucket: 'ilkmobilapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA757f8LFC5zZQXzcDeWFJjWFaqjLU6luo',
    appId: '1:422986280730:ios:906e8c936872aa4a8706a3',
    messagingSenderId: '422986280730',
    projectId: 'ilkmobilapp',
    storageBucket: 'ilkmobilapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMobilAppTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA757f8LFC5zZQXzcDeWFJjWFaqjLU6luo',
    appId: '1:422986280730:ios:906e8c936872aa4a8706a3',
    messagingSenderId: '422986280730',
    projectId: 'ilkmobilapp',
    storageBucket: 'ilkmobilapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMobilAppTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxUMb24P7TtfpvnEu9WJ-NJlVpj7_tPps',
    appId: '1:422986280730:web:932f1ac1f00bc3968706a3',
    messagingSenderId: '422986280730',
    projectId: 'ilkmobilapp',
    authDomain: 'ilkmobilapp.firebaseapp.com',
    storageBucket: 'ilkmobilapp.firebasestorage.app',
    measurementId: 'G-00H1WPPWPV',
  );
}
